apiVersion: "kubeflow.caicloud.io/v1alpha1"
kind: "TFJob"
metadata:
  name: "dist-training-job"
spec:
  tfReplicaSpec:
  - replicas: 2
    tfReplicaType: PS
    template:
      spec:
        containers:
        - name: tensorflow
          image: cargo.caicloud.io/clever-base/tensorflow:v1.4.0-example
          command: ["python", "/opt/mnist/mnist_replica.py"]
          ports:
          - containerPort: 2222
  - replicas: 4
    tfReplicaType: Worker
    template:
      spec:
        containers:
        - name: tensorflow
          image: cargo.caicloud.io/clever-base/tensorflow:v1.4.0-example
          command: ["python", "/opt/mnist/mnist_replica.py"]
          args:
          - "--data_dir=/opt/mnist-data"
          ports:
          - containerPort: 2222
        restartPolicy: OnFailure
