apiVersion: "kubeflow.caicloud.io/v1alpha1"
kind: "TFJob"
metadata:
  name: "local-training-job"
spec:
  tfReplicaSpec:
  - replicas: 1
    tfReplicaType: Local
    template:
      spec:
        containers:
        - name: tensorflow
          image: cargo.caicloud.io/clever-base/tensorflow:v1.4.0-example
          command: ["python", "/opt/mnist/mnist_softmax.py"]
        restartPolicy: OnFailure
