apiVersion: "kubeflow.caicloud.io/v1alpha1"
kind: "TFJob"
metadata:
  name: "training-job"
spec:
  type: Training
  tfReplicaSpec:
  - replicas: 1
    tfReplicaType: Local
    template:
      spec:
        containers:
        - name: tensorflow
          image: cargo.caicloud.io/clever-base/mnist-softmax-cpu:1.0
        restartPolicy: OnFailure
